export type { default as IClass } from './IClass';
export type { default as IClassDetail } from './IClassDetail';
export type { default as ICourseNeedRegister } from './ICourseNeedRegister';
export type { default as ICourseType } from './ICourseType';
export type { default as IGetClassDetails } from './IGetClassDetails';
export type { default as IGetClasses } from './IGetClasses';
export type { default as IGetRegisteredClasses } from './IGetRegisteredClasses';
export type { default as IGetSubjects } from './IGetSubjects';
export type { default as IRegisteredClass } from './IRegisteredClass';
